#SPDX-License-Identifier: MIT-0
# tasks file for nginx-playbook

---
- name: Install NGINX
  apt:
    name: nginx
    state: present
    update_cache: true

- name: Comment out sites-enabled include in nginx.conf
  replace:
    path: /etc/nginx/nginx.conf
    regexp: '^\s*include\s+/etc/nginx/sites-enabled/\*;'
    replace: '# \g<0>'
    backup: yes

- name: Create site1 root directory
  file:
    path: /var/www/site1
    state: directory

- name: Create site2 root directory
  file:
    path: /var/www/site2
    state: directory

- name: Add index.html for site1
  copy:
    content: "<h1>Welcome to Site 1</h1>"
    dest: /var/www/site1/index.html

- name: Add index.html for site2
  copy:
    content: "<h1>Welcome to Site 2</h1>"
    dest: /var/www/site2/index.html

- name: Copy virtual host config for site1
  copy:
    src: site1.com.conf
    dest: /etc/nginx/conf.d/site1.com.conf

- name: Copy virtual host config for site2
  copy:
    src: site2.com.conf
    dest: /etc/nginx/conf.d/site2.com.conf

- name: Test NGINX configuration
  command: nginx -t
  register: nginx_test
  changed_when: false
  failed_when: "'successful' not in nginx_test.stderr"

- name: Reload NGINX
  service:
    name: nginx
    state: reloaded

